### ISSUE TITLE
[iOS] It does not return similarity percentage via camera stream feed on iOS device

### ISSUE THREAD

**Issue by Nicholastx96** [lowapple/flutter-pixelmatching#9]
Hi, thanks for the hard work!

Just a quick question, when using the example app to test out the feature before implementing my own, I've noticed that even if both image1 and the camera feed are exactly the same, it will not return any similarity, nor did the similarity percentage change whatsoever. Furthermore, even after changing from 'All Symbols' to 'Non-Global Symbols', the following error still occurs.

```
Unknown chipRevisionID (0xffffffff)
Attempted to change to mode Portrait with an unsupported device (BackWideDual). Auto device for both positions unsupported, returning Auto device for same position anyway (BackAuto).
Attempted to change to mode Portrait with an unsupported device (BackWideDual). Auto device for both positions unsupported, returning Auto device for same position anyway (BackAuto).
Attempted to change to mode Portrait with an unsupported device (BackAuto). Auto device for both positions unsupported, returning Auto device for same position anyway (BackAuto).
Attempted to change to mode Portrait with an unsupported device (BackWideDual). Auto device for both positions unsupported, returning Auto device for same position anyway (BackAuto).
[ERROR:flutter/runtime/dart_isolate.cc(1107)] Unhandled exception:
Invalid argument(s): Failed to lookup symbol 'initialize': dlsym(RTLD_DEFAULT, initialize): symbol not found
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:33:70)
#1      PixelMatchingBindings._initializePtr (package:flutter_pixelmatching/src/pixelmatching_bindings.dart:29:55)
#2      PixelMatchingBindings._initializePtr (package:flutter_pixelmatching/src/pixelmatching_bindings.dart)
#3      PixelMatchingBindings._initialize (package:flutter_pixelmatching/src/pixelmatching_bindings.dart:30:28)
#4      PixelMatchingBindings._initialize (package:flutter_pixelmatching/src/pixelmatching_bindings.dart)
#5      PixelMatchingBindings.initialize (package:flutter_pixelmatching/src/pixelmatching_bindings.dart:25:12)
#6      _PixelMatchingClient.initialize (package:flutter_pixelmatching/src/pixelmatching_client.dart:127:13)
#7      _handleMessage (package:flutter_pixelmatching/src/pixelmatching_client.dart:65:17)
#8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#11     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#12     _StreamController._add (dart:async/stream_controller.dart:658:7)
#13     _StreamController.add (dart:async/stream_controller.dart:606:5)
#14     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
The selected imageFormatGroup is not supported by iOS. Defaulting to brga8888
```

Environment:
iPhone 14 Pro Max ( iOS 17.4.1)
Flutter 3.19.5
Dart 3.3.3

![IMG_5630](https://github.com/lowapple/flutter-pixelmatching/assets/88279595/06de4e4e-c9b2-449a-8e0c-1caad66abc88)

**Comment by lowapple** [comment]
@Nicholastx96 
Hi, sorry for the delay in replying.
I've tried this and that, but it didn't happen.
It might have happened in XCode. Could you please check it for me.

Environment:
iPhone 13 Pro ( iOS 17.4.1 )
Flutter 3.19.5
Dart 3.3.3 
XCode 15.2

**Comment by Nicholastx96** [comment]
@lowapple 
Thanks for the reply!
I've tried with XCode 15.3 and clean my xcode before rebuilding it.
But still no luck so far :(

Environment:
iPhone 14 Pro Max ( iOS 17.4.1)
Flutter 3.19.5
Dart 3.3.3
XCode 15.3

**Comment by lowapple** [comment]
@Nicholastx96 
Can you downgrade to XCode 15.2 to test it out?
